FROM node:20-alpine AS builder

WORKDIR /app

# Copy root configurations
COPY package*.json tsconfig.json ./
COPY packages/ ./packages/
COPY apps/api/ ./apps/api/

RUN npm install
RUN npm run build -w @betoch/shared
RUN npm run build -w @betoch/validation
RUN npm run build -w @betoch/config
RUN npm run build -w @betoch/api

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app /app

EXPOSE 4000
CMD ["npm", "run", "start", "-w", "@betoch/api"]
